development:
  adapter: postgresql
  encoding: unicode
  database: balboa_dev
  pool: 5
  username: postgres
  password: 
  host: localhost
test:
  adapter: postgresql
  encoding: unicode
  database: balboa_test
  pool: 5
  username: postgres
  password:
  host: localhost
production:
  adapter: postgresql
  encoding: unicode
  database: balboa_prod
  pool: 5
  username: postgres
  password: ENV['POSTGRES_PASSWORD']
  host: localhost