# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f0b1d7928157d736ca2a510256e47adb0e9c397cf4aeea382b0c23d36af6ae634a99020174329a89c1b9f370c438ee98381c6878bb037397c019717a19e063c

test:
  secret_key_base: ec7e319f5af4b507b6079b868a2f4f4607e918244544eb8015a6d980780963481a12f68025295944fa29e74d87ac3011ae78656269cd165fb233f6f3e36069f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
